name: Continuous integration

on:
  push:
    branches: [ 'feature/#**' ]
  pull_request:
    branches: [ 'feature/#**' ]

jobs:
  integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      
      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: "Install dependencies"
        run: "npm install"
      
      - name: "Create .env file"
        run: |
          touch .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
          echo COINMARKETCAP=${{ secrets.COINMARKETCAP_KEY }} >> .env
      
      - name: "Run linter"
        run: "npm run lint"
      
      - name: "Generate TypeChain bindings"
        run: "npm run generate:types"

      - name: "Test the contracts"
        run: "npm test"
      
      - name: "Check the gas usage of the contracts"
        run: "npm run test:gas"
